game : ../source/game.cpp ../source/ThreadSafeQueue.cpp ../source/dila.hpp
	g++ ../source/game.cpp ../source/ThreadSafeQueue.cpp ../source/dila.hpp -std=c++0x -o ../target/game -g -lpthread

all: game
clean:
	rm -f ../target/game

